apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tnlu1tzq6-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:3fb2f6c00a50fa6bb06695e5ef25217e0ec07c40@sha256:8475955d8adb16061620b04ad76540dd2ff0cf294a25031908a9cf8b22bebe06
          name: container-image
