apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tnlu1tzq6-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tnlu1tzq6-python 
  name: tnlu1tzq6-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tnlu1tzq6-python 
